using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

namespace Problema2
{
    public class PE2
    {
        public static void Main(string[] args)
        {
            long resultado = 3;
            long i = 3;
            while( resultado < 10)
            {
                resultado = 0;
                
            }
            Console.WriteLine("El resultado es {0}", (resultado +3));
            Console.ReadLine();
	    }
    }
}
    

